### ISSUE TITLE
Is there aptitude repository for ktmpl?

### ISSUE THREAD

**Issue by zdraganov** [InQuicker/ktmpl#19]
Hello folks!
I'm looking for tool like this for our CI environment.
I'm wondering if there is aptitude repository for the package?

**Comment by jimmycuadra** [comment]
No, there isn't—at least not one we maintain. We do provide precompiled binaries which should make it relatively easy to add to a build environment, assuming that environment is x86_64 Linux: https://github.com/InQuicker/ktmpl/releases. We also maintain a public Docker image, if that's a viable route for you.
