### ISSUE TITLE
how to handle spaces in variables?

### ISSUE THREAD

**Issue by JeanMertz** [InQuicker/ktmpl#6]
It seems like it's difficult/impossible(?) to handle spaces in variables.

Is this correct, or is there some way to work with spaces?

**Comment by jimmycuadra** [comment]
This occurred to me before, just haven't addressed it yet. You are right that it's not possible right now.

**Comment by JeanMertz** [comment]
Thanks for the heads-up 👍 

Same goes for newlines by the way, which is important for something like cert/key files.

**Comment by jimmycuadra** [comment]
I'm not sure off hand if clap supports this pattern, but how I imagine it working is:

```
ktmpl FILE --parameter KEY VALUE KEY VALUE KEY VALUE
```

If each invocation of the parameter option takes two values like that, then clap can handle splitting the key and value for each pair and you can use normal shell constructs like quoting and sub-shells to produce both the keys and values.
