### ISSUE TITLE
Parameter format

### ISSUE THREAD

**Issue by lithiumFlower** [InQuicker/ktmpl#8]
I am trying to use ktmpl to parse parameters like this:
`ktmpl template_path -p APP_PARAMS "--param1 --param2 --etc"`

Unfortunately this doesn't work. For instance the above command would result in an error:
`error: Found argument '--param1 --param2 --etc' which wasn't expected, or isn't valid in this context`

Can this be supported?

**Comment by jimmycuadra** [comment]
I've run into this issue, too. For me it happened when one of the values was a PEM file. The error comes from clap, the CLI argument parser ktmpl uses. @kbknapp, is there a way to escape the leading hyphens on a value so clap doesn't think it's an option/flag?

**Comment by kbknapp** [comment]
@jimmycuadra [there is an option](http://kbknapp.github.io/clap-rs/clap/enum.AppSettings.html#variant.AllowLeadingHyphen) for that, but it should be used with caution and some design forethought because it can hide what would otherwise be an error.

**Comment by lithiumFlower** [comment]
@jimmycuadra Do you know if anyone is actively working on this?

**Comment by lithiumFlower** [comment]
I patched it myself for my own work, feel free to steal (it's literally one line)
https://github.com/lithiumFlower/ktmpl/commit/93737f75ae921f56da015bc99c00d6c252b98753

**Comment by jimmycuadra** [comment]
Released in [0.4.1](https://github.com/InQuicker/ktmpl/releases/tag/0.4.1)
